import * as dotenv from "dotenv";
dotenv.config();

import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({
	connectionString: process.env.DATABASE_URL!,
});
const db = new PrismaClient({ adapter });

async function main() {
	// ── Zones ──────────────────────────────────────────────────────────────────
	await db.zone.upsert({
		where: { id: "z1" },
		update: {},
		create: { id: "z1", name: "Salón Principal", order: 0 },
	});
	await db.zone.upsert({
		where: { id: "z2" },
		update: {},
		create: { id: "z2", name: "Afuera", order: 1 },
	});

	// ── Tables ─────────────────────────────────────────────────────────────────
	const tables = [
		{
			id: "t1",
			zoneId: "z1",
			number: 1,
			type: "bar",
			seats: 4,
			x: 80,
			y: 80,
			w: 90,
			h: 60,
		},
		{
			id: "t2",
			zoneId: "z1",
			number: 2,
			type: "bar",
			seats: 6,
			x: 210,
			y: 80,
			w: 90,
			h: 60,
		},
		{
			id: "t3",
			zoneId: "z1",
			number: 3,
			type: "pool",
			seats: 2,
			x: 340,
			y: 60,
			w: 140,
			h: 80,
		},
		{
			id: "t4",
			zoneId: "z1",
			number: 4,
			type: "bar",
			seats: 4,
			x: 80,
			y: 180,
			w: 90,
			h: 60,
		},
		{
			id: "t5",
			zoneId: "z1",
			number: 5,
			type: "pool",
			seats: 2,
			x: 210,
			y: 180,
			w: 140,
			h: 80,
		},
		{
			id: "t6",
			zoneId: "z1",
			number: 6,
			type: "bar",
			seats: 8,
			x: 80,
			y: 280,
			w: 120,
			h: 60,
		},
		{
			id: "t7",
			zoneId: "z1",
			number: 7,
			type: "bar",
			seats: 4,
			x: 250,
			y: 280,
			w: 90,
			h: 60,
		},
		{
			id: "t8",
			zoneId: "z1",
			number: 8,
			type: "bar",
			seats: 4,
			x: 380,
			y: 200,
			w: 90,
			h: 60,
		},
		{
			id: "t9",
			zoneId: "z2",
			number: 9,
			type: "bar",
			seats: 6,
			x: 80,
			y: 80,
			w: 90,
			h: 60,
		},
		{
			id: "t10",
			zoneId: "z2",
			number: 10,
			type: "pool",
			seats: 2,
			x: 210,
			y: 60,
			w: 140,
			h: 80,
		},
		{
			id: "t11",
			zoneId: "z2",
			number: 11,
			type: "bar",
			seats: 4,
			x: 80,
			y: 180,
			w: 90,
			h: 60,
		},
		{
			id: "t12",
			zoneId: "z2",
			number: 12,
			type: "bar",
			seats: 4,
			x: 210,
			y: 180,
			w: 90,
			h: 60,
		},
	];
	for (const t of tables) {
		await db.table.upsert({
			where: { id: t.id },
			update: {},
			create: { ...t, status: "available" },
		});
	}

	// ── Categories ─────────────────────────────────────────────────────────────
	const categories = [
		// ── Tragos ──
		{ id: "c1", name: "Recomendados", icon: "🍹", order: 0 },
		{ id: "c1b", name: "De Autor", icon: "✨", order: 1 },
		{ id: "c1c", name: "Directos", icon: "🧊", order: 2 },
		{ id: "c1d", name: "Clásicos", icon: "🥂", order: 3 },
		// ── Bebidas ──
		{ id: "c2", name: "Cervezas", icon: "🍺", order: 4 },
		{ id: "c4", name: "Medidas", icon: "🥃", order: 5 },
		{ id: "c4b", name: "Bottle Service", icon: "🍾", order: 6 },
		{ id: "c3", name: "Vinos & Espumantes", icon: "🍷", order: 7 },
		{ id: "c6", name: "Sin Alcohol", icon: "🥤", order: 8 },
		// ── Comida ──
		{ id: "c5a", name: "Hamburguesas", icon: "🍔", order: 9 },
		{ id: "c5b", name: "Sandwiches", icon: "🥪", order: 10 },
		{ id: "c5c", name: "Mex & Wraps", icon: "🌯", order: 11 },
		{ id: "c5d", name: "Tapas", icon: "🍟", order: 12 },
		{ id: "c5e", name: "Barbacoas", icon: "🔥", order: 13 },
		{ id: "c5f", name: "Tablas", icon: "🪵", order: 14 },
		// ── Pool ──
		{ id: "c7", name: "Pool", icon: "🎱", order: 15 },
	];
	for (const c of categories) {
		await db.category.upsert({
			where: { id: c.id },
			update: { name: c.name, icon: c.icon, order: c.order },
			create: c,
		});
	}

	// ── Products ───────────────────────────────────────────────────────────────
	type ProductSeed = {
		id: string;
		name: string;
		categoryId: string;
		target: string;
		price: number;
		description: string | null;
		isAvailable: boolean;
		isPoolChip: boolean;
	};
	const products: ProductSeed[] = [
		// ── Tragos: Recomendados ──────────────────────────────────────────────
		{
			id: "p1",
			name: "Daiquiri Frozen",
			categoryId: "c1",
			target: "bar",
			price: 7000,
			description: "Almíbar, limón, ron, pulpa",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p2",
			name: "Mojito Clásico",
			categoryId: "c1",
			target: "bar",
			price: 7000,
			description: "Almíbar, limón, ron, menta, soda",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p3",
			name: "Mojito Cubano",
			categoryId: "c1",
			target: "bar",
			price: 7000,
			description: "Almíbar, limón, ron, menta, soda, bitter angostura",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p4",
			name: "Mojito Frutal",
			categoryId: "c1",
			target: "bar",
			price: 8000,
			description: "Azúcar, limón, ron, menta, pulpa, soda",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p5",
			name: "Cynar Julep",
			categoryId: "c1",
			target: "bar",
			price: 7000,
			description: "Azúcar, limón, menta, cynar, jugo de pomelo",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p6",
			name: "Caipirinha",
			categoryId: "c1",
			target: "bar",
			price: 7000,
			description: "Lima, azúcar, cachaça",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p7",
			name: "Caipiroska",
			categoryId: "c1",
			target: "bar",
			price: 7000,
			description: "Lima, azúcar, vodka",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p8",
			name: "Garcia Batido",
			categoryId: "c1",
			target: "bar",
			price: 7000,
			description: "Almíbar, limón, gancia",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Tragos: De Autor ─────────────────────────────────────────────────
		{
			id: "p9",
			name: "Hibiscus Tonic",
			categoryId: "c1b",
			target: "bar",
			price: 8500,
			description: "Almíbar de hibiscus, maracuyá, tónica",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p10",
			name: "Tirillín",
			categoryId: "c1b",
			target: "bar",
			price: 8000,
			description: "Almíbar, limón, vermouth rosado, vino tinto, seven up",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p11",
			name: "Froshy Beer",
			categoryId: "c1b",
			target: "bar",
			price: 9000,
			description: "Almíbar, campari, vermouth rosso, espuma de cerveza",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p12",
			name: "My Way Passion",
			categoryId: "c1b",
			target: "bar",
			price: 9000,
			description: "Almíbar, maracuyá, whisky, bitter angostura",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Tragos: Directos ─────────────────────────────────────────────────
		{
			id: "p13",
			name: "Fernet con Coca",
			categoryId: "c1c",
			target: "bar",
			price: 8000,
			description: "Fernet Branca + Coca-Cola",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p14",
			name: "Aperol Spritz",
			categoryId: "c1c",
			target: "bar",
			price: 7000,
			description: "Espumante, aperol, soda",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p15",
			name: "Cuba Libre",
			categoryId: "c1c",
			target: "bar",
			price: 7000,
			description: "Ron, coca cola",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p16",
			name: "Gin Tónico",
			categoryId: "c1c",
			target: "bar",
			price: 7000,
			description: "Gin, campari, tónica",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p17",
			name: "Garibaldi",
			categoryId: "c1c",
			target: "bar",
			price: 7000,
			description: "Campari, jugo de naranja",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p18",
			name: "Whiscoca",
			categoryId: "c1c",
			target: "bar",
			price: 7000,
			description: "Whisky, coca cola",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Tragos: Clásicos ─────────────────────────────────────────────────
		{
			id: "p19",
			name: "Negroni",
			categoryId: "c1d",
			target: "bar",
			price: 8500,
			description: "Gin, campari, vermouth rosso",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p20",
			name: "Old Fashioned",
			categoryId: "c1d",
			target: "bar",
			price: 8500,
			description: "Azúcar, whisky, bitter angostura",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p21",
			name: "Boulevardier",
			categoryId: "c1d",
			target: "bar",
			price: 8500,
			description: "Whisky, campari, vermouth",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p22",
			name: "Tom Collins",
			categoryId: "c1d",
			target: "bar",
			price: 8000,
			description: "Gin, almíbar, limón, soda",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p23",
			name: "Penicillin",
			categoryId: "c1d",
			target: "bar",
			price: 8500,
			description: "Whisky, limón, miel, jengibre",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p24",
			name: "Mint Julep",
			categoryId: "c1d",
			target: "bar",
			price: 7000,
			description: "Almíbar, limón, menta, whisky, soda",
			isAvailable: true,
			isPoolChip: false,
		},

		// ── Cervezas: Litros ─────────────────────────────────────────────────
		{
			id: "p30",
			name: "Budweiser Litro",
			categoryId: "c2",
			target: "bar",
			price: 8000,
			description: "Litro",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p31",
			name: "Stella Artois Litro",
			categoryId: "c2",
			target: "bar",
			price: 10000,
			description: "Litro",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p32",
			name: "Andes Litro",
			categoryId: "c2",
			target: "bar",
			price: 9000,
			description: "Rubia / IPA / Roja",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Cervezas: Latas 473cc ────────────────────────────────────────────
		{
			id: "p33",
			name: "Quilmes Lata",
			categoryId: "c2",
			target: "bar",
			price: 3000,
			description: "473cc",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p34",
			name: "Brahma Lata",
			categoryId: "c2",
			target: "bar",
			price: 3000,
			description: "473cc",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p35",
			name: "Budweiser Lata",
			categoryId: "c2",
			target: "bar",
			price: 4000,
			description: "473cc",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p36",
			name: "Stella Artois Lata",
			categoryId: "c2",
			target: "bar",
			price: 4000,
			description: "473cc",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p37",
			name: "Patagonia Bohemian",
			categoryId: "c2",
			target: "bar",
			price: 4000,
			description: "473cc",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p38",
			name: "Stella Noire",
			categoryId: "c2",
			target: "bar",
			price: 5000,
			description: "473cc",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p39",
			name: "Temple Wolf IPA",
			categoryId: "c2",
			target: "bar",
			price: 5000,
			description: "473cc · Artesanal",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p40",
			name: "Corona",
			categoryId: "c2",
			target: "bar",
			price: 5000,
			description: "330ml",
			isAvailable: true,
			isPoolChip: false,
		},

		// ── Vinos & Espumantes ───────────────────────────────────────────────
		{
			id: "p45",
			name: "Benjamin Malbec",
			categoryId: "c3",
			target: "bar",
			price: 15000,
			description: "Botella",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p46",
			name: "Benjamin Chardonnay",
			categoryId: "c3",
			target: "bar",
			price: 15000,
			description: "Botella",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p47",
			name: "Nicasio",
			categoryId: "c3",
			target: "bar",
			price: 15000,
			description: "Botella",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p48",
			name: "Novecientos",
			categoryId: "c3",
			target: "bar",
			price: 16000,
			description: "Botella",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p49",
			name: "Extra Brut",
			categoryId: "c3",
			target: "bar",
			price: 17000,
			description: "Espumante",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p50",
			name: "Chandon",
			categoryId: "c3",
			target: "bar",
			price: 30000,
			description: "Espumante premium",
			isAvailable: true,
			isPoolChip: false,
		},

		// ── Medidas ──────────────────────────────────────────────────────────
		{
			id: "p55",
			name: "Red Label",
			categoryId: "c4",
			target: "bar",
			price: 5500,
			description: "Medida de whisky",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p56",
			name: "Black Label",
			categoryId: "c4",
			target: "bar",
			price: 7500,
			description: "Medida de whisky",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p57",
			name: "Double Black",
			categoryId: "c4",
			target: "bar",
			price: 8500,
			description: "Medida de whisky",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p58",
			name: "Jack Daniel's",
			categoryId: "c4",
			target: "bar",
			price: 7500,
			description: "Medida",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p59",
			name: "Jameson",
			categoryId: "c4",
			target: "bar",
			price: 5500,
			description: "Medida",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p60",
			name: "Jim Beam",
			categoryId: "c4",
			target: "bar",
			price: 5000,
			description: "Medida",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p61",
			name: "J&B",
			categoryId: "c4",
			target: "bar",
			price: 5000,
			description: "Medida",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p62",
			name: "Ballantines",
			categoryId: "c4",
			target: "bar",
			price: 5500,
			description: "Medida",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p63",
			name: "Bailey's",
			categoryId: "c4",
			target: "bar",
			price: 5500,
			description: "Medida",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Bottle Service ───────────────────────────────────────────────────
		{
			id: "p64",
			name: "Fernet Branca + Coca",
			categoryId: "c4b",
			target: "bar",
			price: 60000,
			description: "Botella completa",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p65",
			name: "Havana Club + Coca",
			categoryId: "c4b",
			target: "bar",
			price: 60000,
			description: "Botella completa",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p66",
			name: "Red Label + Coca/Speed",
			categoryId: "c4b",
			target: "bar",
			price: 65000,
			description: "Botella completa",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p67",
			name: "Black Label + Coca/Speed",
			categoryId: "c4b",
			target: "bar",
			price: 75000,
			description: "Botella completa",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p68",
			name: "Jagermeister + Speed",
			categoryId: "c4b",
			target: "bar",
			price: 80000,
			description: "Botella completa",
			isAvailable: true,
			isPoolChip: false,
		},

		// ── Comida: Hamburguesas (con fritas) ────────────────────────────────
		{
			id: "p70",
			name: "Americana",
			categoryId: "c5a",
			target: "kitchen",
			price: 15000,
			description:
				"Doble carne, panceta, cheddar, cebolla caramelizada, huevo, salsa picante",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p71",
			name: "Criolla",
			categoryId: "c5a",
			target: "kitchen",
			price: 16000,
			description:
				"Doble carne, provoleta, tomate asado, cebolla caramelizada, huevo a la plancha",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p72",
			name: "Double",
			categoryId: "c5a",
			target: "kitchen",
			price: 16000,
			description: "Doble carne, doble panceta, doble queso, salsa BBQ",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p73",
			name: "Tex Mex",
			categoryId: "c5a",
			target: "kitchen",
			price: 16000,
			description:
				"Doble carne, cheddar, morrones asados, salsa criolla, salsa picante",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p74",
			name: "Cheese Burger",
			categoryId: "c5a",
			target: "kitchen",
			price: 13000,
			description: "Con fritas",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p75",
			name: "Burger de Falafel",
			categoryId: "c5a",
			target: "kitchen",
			price: 12000,
			description:
				"Medallón de garbanzos, rúcula, morrones asados, pickles, salsa ali oli",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Comida: Sandwiches (con fritas) ─────────────────────────────────
		{
			id: "p76",
			name: "Pulled Pork",
			categoryId: "c5b",
			target: "kitchen",
			price: 15000,
			description:
				"Bondiola desmechada, panceta, barbacoa, pickles de cebolla, cheddar",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p77",
			name: "Cheese Philly Steak",
			categoryId: "c5b",
			target: "kitchen",
			price: 15000,
			description:
				"Ternera salteada, cebolla, morrón, cheddar, pickles de pepino",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p78",
			name: "Chicken Sandwich",
			categoryId: "c5b",
			target: "kitchen",
			price: 15000,
			description: "Pollo, cheddar, lechuga, tomate, mayonesa, honey mustard",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Comida: Mex & Wraps (con fritas) ────────────────────────────────
		{
			id: "p79",
			name: "Burrito Tex Way",
			categoryId: "c5c",
			target: "kitchen",
			price: 15000,
			description: "Ternera, arroz, sour cream, tomate, cebolla, salsa picante",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p80",
			name: "Wrap Chicken Caesar",
			categoryId: "c5c",
			target: "kitchen",
			price: 15000,
			description: "Lechuga crocante, pollo grillado, parmesano, salsa caesar",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p81",
			name: "Quesadilla de Cerdo",
			categoryId: "c5c",
			target: "kitchen",
			price: 15000,
			description: "Bondiola desmechada, mix de queso, cebolla caramelizada",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p82",
			name: "Quesadilla Vegetariana",
			categoryId: "c5c",
			target: "kitchen",
			price: 13000,
			description: "Queso tybo y cheddar, espinaca, tomate, choclo tostado",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Comida: Tapas ────────────────────────────────────────────────────
		{
			id: "p83",
			name: "Papas Fritas",
			categoryId: "c5d",
			target: "kitchen",
			price: 10000,
			description: null,
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p84",
			name: "Papas c/ Cheddar",
			categoryId: "c5d",
			target: "kitchen",
			price: 11000,
			description: null,
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p85",
			name: "Papas My Way",
			categoryId: "c5d",
			target: "kitchen",
			price: 17000,
			description: "Cheddar, panceta, cebolla de verdeo, huevo a la plancha",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p86",
			name: "Tortilla de Papas",
			categoryId: "c5d",
			target: "kitchen",
			price: 12000,
			description: null,
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p87",
			name: "Karaage",
			categoryId: "c5d",
			target: "kitchen",
			price: 18000,
			description: "Bocados de pollo en tempura crocante",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p88",
			name: "Rabas",
			categoryId: "c5d",
			target: "kitchen",
			price: 13000,
			description: "Con dips de salsa a elección",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p89",
			name: "Bastones de Muzzarella",
			categoryId: "c5d",
			target: "kitchen",
			price: 13000,
			description: "Con dips de salsa a elección",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p90",
			name: "Buñuelos de Espinaca",
			categoryId: "c5d",
			target: "kitchen",
			price: 13000,
			description: "Rellenos, semillas y muzzarella",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Comida: Barbacoas ────────────────────────────────────────────────
		{
			id: "p91",
			name: "BBQ Wings",
			categoryId: "c5e",
			target: "kitchen",
			price: 13000,
			description: "Alitas ahumadas con salsa barbacoa",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p92",
			name: "BBQ Ribs",
			categoryId: "c5e",
			target: "kitchen",
			price: 20000,
			description: "Costillas de cerdo con salsa barbacoa de ananá",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Comida: Tablas ───────────────────────────────────────────────────
		{
			id: "p93",
			name: "Combo X2",
			categoryId: "c5f",
			target: "kitchen",
			price: 35000,
			description: "BBQ ribs, BBQ wings, karaage y papas",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p94",
			name: "Combo X4",
			categoryId: "c5f",
			target: "kitchen",
			price: 70000,
			description: "2 porciones BBQ ribs, BBQ wings, karaage y papas",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p95",
			name: "Combo Vegetariano",
			categoryId: "c5f",
			target: "kitchen",
			price: 28000,
			description:
				"Tortilla, bastones de muzzarella, buñuelos de espinaca y papas",
			isAvailable: true,
			isPoolChip: false,
		},

		// ── Sin Alcohol: Mocktails ───────────────────────────────────────────
		{
			id: "p100",
			name: "Mocktail Frutal",
			categoryId: "c6",
			target: "bar",
			price: 5000,
			description: "Almíbar, limón, pulpa de fruta, soda",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p101",
			name: "Limonada Honey",
			categoryId: "c6",
			target: "bar",
			price: 5500,
			description: "Almíbar de miel, limón, agua",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p102",
			name: "Té de Hibiscus",
			categoryId: "c6",
			target: "bar",
			price: 5500,
			description: "Almíbar, limón, soda",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p103",
			name: "Limonada",
			categoryId: "c6",
			target: "bar",
			price: 5000,
			description: "Menta, jengibre, almíbar, limón, agua",
			isAvailable: true,
			isPoolChip: false,
		},
		// ── Sin Alcohol: Bebidas ─────────────────────────────────────────────
		{
			id: "p104",
			name: "Gaseosa",
			categoryId: "c6",
			target: "bar",
			price: 3000,
			description: "Línea Pepsi 500ml",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p105",
			name: "Agua sin gas",
			categoryId: "c6",
			target: "bar",
			price: 3000,
			description: "500ml",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p106",
			name: "Agua con gas",
			categoryId: "c6",
			target: "bar",
			price: 3000,
			description: "500ml",
			isAvailable: true,
			isPoolChip: false,
		},
		{
			id: "p107",
			name: "Speed",
			categoryId: "c6",
			target: "bar",
			price: 4000,
			description: "Energizante 250ml",
			isAvailable: true,
			isPoolChip: false,
		},

		// ── Pool ─────────────────────────────────────────────────────────────
		{
			id: "p110",
			name: "Ficha de Pool",
			categoryId: "c7",
			target: "bar",
			price: 1200,
			description: "1 partida (30 min)",
			isAvailable: true,
			isPoolChip: true,
		},
	];

	for (const p of products) {
		await db.product.upsert({
			where: { id: p.id },
			update: {
				name: p.name,
				categoryId: p.categoryId,
				target: p.target,
				price: p.price,
				description: p.description,
				isAvailable: p.isAvailable,
				isPoolChip: p.isPoolChip,
			},
			create: p,
		});
	}

	// ── Staff ──────────────────────────────────────────────────────────────────
	const staff = [
		{ id: "s1", name: "Martín García", role: "cashier", avatar: "MG" },
		{ id: "s2", name: "Lucía Fernández", role: "waiter", avatar: "LF" },
		{ id: "s3", name: "Diego López", role: "waiter", avatar: "DL" },
		{ id: "s4", name: "Ana Torres", role: "kitchen", avatar: "AT" },
		{ id: "s5", name: "Carlos Ruiz", role: "bar", avatar: "CR" },
		{ id: "s6", name: "Valentina Paz", role: "admin", avatar: "VP" },
	];
	for (const s of staff) {
		await db.staff.upsert({ where: { id: s.id }, update: {}, create: s });
	}

	// ── Ingredients ────────────────────────────────────────────────────────────
	const ingredients = [
		{
			id: "ing1",
			name: "Fernet Branca",
			unit: "ml",
			stockCurrent: 4800,
			alertThreshold: 1500,
			costPerUnit: 0.025,
		},
		{
			id: "ing2",
			name: "Ron Havana Club",
			unit: "ml",
			stockCurrent: 3200,
			alertThreshold: 800,
			costPerUnit: 0.032,
		},
		{
			id: "ing3",
			name: "Vodka",
			unit: "ml",
			stockCurrent: 2100,
			alertThreshold: 600,
			costPerUnit: 0.02,
		},
		{
			id: "ing4",
			name: "Gin Brighton",
			unit: "ml",
			stockCurrent: 820,
			alertThreshold: 1000,
			costPerUnit: 0.038,
		},
		{
			id: "ing5",
			name: "Whisky Red Label",
			unit: "ml",
			stockCurrent: 1600,
			alertThreshold: 800,
			costPerUnit: 0.042,
		},
		{
			id: "ing6",
			name: "Whisky Black Label",
			unit: "ml",
			stockCurrent: 1100,
			alertThreshold: 500,
			costPerUnit: 0.058,
		},
		{
			id: "ing7",
			name: "Aperol",
			unit: "ml",
			stockCurrent: 1650,
			alertThreshold: 600,
			costPerUnit: 0.029,
		},
		{
			id: "ing8",
			name: "Campari",
			unit: "ml",
			stockCurrent: 1200,
			alertThreshold: 500,
			costPerUnit: 0.031,
		},
		{
			id: "ing9",
			name: "Vermouth Rosso",
			unit: "ml",
			stockCurrent: 900,
			alertThreshold: 400,
			costPerUnit: 0.018,
		},
		{
			id: "ing10",
			name: "Tónica artesanal",
			unit: "ml",
			stockCurrent: 3600,
			alertThreshold: 2000,
			costPerUnit: 0.008,
		},
		{
			id: "ing11",
			name: "Lima",
			unit: "units",
			stockCurrent: 28,
			alertThreshold: 20,
			costPerUnit: 45,
		},
		{
			id: "ing12",
			name: "Menta",
			unit: "gr",
			stockCurrent: 180,
			alertThreshold: 100,
			costPerUnit: 0.8,
		},
		{
			id: "ing13",
			name: "Almíbar",
			unit: "ml",
			stockCurrent: 5000,
			alertThreshold: 1000,
			costPerUnit: 0.003,
		},
		{
			id: "ing14",
			name: "Coca-Cola 2.25L",
			unit: "units",
			stockCurrent: 18,
			alertThreshold: 8,
			costPerUnit: 950,
		},
		{
			id: "ing15",
			name: "Cerveza Quilmes",
			unit: "units",
			stockCurrent: 96,
			alertThreshold: 24,
			costPerUnit: 650,
		},
		{
			id: "ing16",
			name: "Carne hamburguesa",
			unit: "units",
			stockCurrent: 80,
			alertThreshold: 20,
			costPerUnit: 1200,
		},
		{
			id: "ing17",
			name: "Pan brioche",
			unit: "units",
			stockCurrent: 60,
			alertThreshold: 15,
			costPerUnit: 350,
		},
		{
			id: "ing18",
			name: "Papas prefritas",
			unit: "kg",
			stockCurrent: 12,
			alertThreshold: 3,
			costPerUnit: 1800,
		},
		{
			id: "ing19",
			name: "Alitas de pollo",
			unit: "kg",
			stockCurrent: 8,
			alertThreshold: 2,
			costPerUnit: 3200,
		},
		{
			id: "ing20",
			name: "Bondiola",
			unit: "kg",
			stockCurrent: 5,
			alertThreshold: 1.5,
			costPerUnit: 5000,
		},
	];
	for (const i of ingredients) {
		await db.ingredient.upsert({ where: { id: i.id }, update: {}, create: i });
	}

	console.log("Seed completed successfully");
}

main()
	.catch((e) => {
		console.error(e);
		process.exit(1);
	})
	.finally(async () => {
		await db.$disconnect();
	});
